id: dot-config-exposed
filter: true
info:
  name: Dot Config Exposed
  risk: Potential
  confidence: Tentative

params:
  - root: "{{.BaseURL}}"

origin:
  method: GET
  redirect: false
  headers:
    - User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
  url: >-
    {{.BaseURL}}/hopefully404.config

variables:
  - secret: |
      web.config
      rebar.config
      packages.config
      App.config
      NuGet.config
      app.config
      nuget.config
      Web.Debug.config
      build.config
      Web.Release.config
      lombok.config
      cabal.config
      cabal.sandbox.config
      Makefile.config
      elvis.config
      doxygen.config
      relx.config
      pdfjs.config
      cake.config
      nextflow.config
      sys.config
      Nuget.config
      epydoc.config
      ApplicationInsights.config
      i3.config
      sinan.config
      pkg.vars.config
      README.config
      test.config
      proxy.config
      sage.config
      lab.config
      default.config
      scaffolding.config
      tup.config
      threshold.config
      NLog.config
      package.config
      Bundle.config
      NuGet.master.config
      log4net.config
      options.config
      reference.config
      classification.config
      plugins.config
      auth.config
      boss.config
      Make.config
      nginx.config
      server.config
      cake.packages.config
      linux.config
      ripple.config
      theme.config
      game.config
      dev.config
      compass.config
      make.config
      rebar-slex.config
      ssh.config
      rabbitmq.config
      basis.config
      gitdm.config
      gum.config
      website.config
      lift-standard.config
      pachamama.config
      reltool.config
      git.config
      lfe.config
      paige.config
      boxstarter.config
      logging.config
      busybox.config
      chocolatey.config
      gopack.config
      project.config
      mongo-orchestration.config
      dockers.config
      xref.config
      versions.config
      jshint.config
      mailcow.config

requests:
  - method: GET
    redirect: false
    headers:
      - User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3984.0 Safari/537.36
    url: >-
      {{.root}}/{{.secret}}
    detections:
      - >-
        Diff() && StatusCode() == 200 && !RegexSearch("response", "(?i)(Oops!|Whoops!|AutodiscoverService|not\sfound|Request\sRejected|Access\sDenied|a\sbad\sURL|has\sbeen\slocked)") && (RegexSearch("resHeaders", "Accept-Ranges.*bytes") || RegexSearch("resHeaders", ".*Content-Type:.*octet-stream") || RegexSearch("resHeaders", "text/plain")) && (Math.abs(ContentLength() - OriginContentLength()) > 200) && !RegexSearch("body", "(?i)(\<\!doctype|\<html|\<head|\<body||\<div)") && ContentLength('body') > 200  && !StringSearch("oresHeaders", "text/plain")
